language: python

matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.13 CASADIVERSION=3.0.0

notifications:
  email: false

# Installation of Numpy 1.8 in Travis CI:
# http://stackoverflow.com/questions/30588634/install-numpy-1-8-in-travis-ci

before_install:
 - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
 - chmod +x miniconda.sh
 - bash miniconda.sh -b -p $HOME/miniconda
 - export PATH=/home/travis/miniconda/bin:$PATH
 - conda update --yes conda

install:
 - conda install --yes numpy=$NUMPY scipy=$SCIPY matplotlib nose mock

# Specific version of coverage (3.7.1) necessary here, higher versions include
# the renaming of a class used by python-coveralls that else won't be found

 - pip --version
 - pip install coverage coveralls python-coveralls nose-cov
 - pip --version

 - wget http://sourceforge.net/projects/casadi/files/CasADi/$CASADIVERSION/linux/casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz/download -O casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz
 - mkdir $HOME/casadi-py27-np1.9.1-v$CASADIVERSION
 - tar -zxvf casadi-py27-np1.9.1-v$CASADIVERSION.tar.gz -C $HOME/casadi-py27-np1.9.1-v$CASADIVERSION

 - export PYTHONPATH=$PYTHONPATH:$HOME/casadi-py27-np1.9.1-v$CASADIVERSION

 - python setup.py install

before_script:

# Fake display for testing the plotting features
# http://docs.travis-ci.com/user/gui-and-headless-browsers/#Using-xvfb-to-Run-Tests-That-Require-a-GUI

 - export DISPLAY=:99.0
 - sh -e /etc/init.d/xvfb start

script:
 - nosetests --exe -v --with-cov

after_success:
 - coveralls --config_file .coveragerc

# deploy:
#   provider: pypi
#   user: "adbuerger"
#   password:
#     secure: rKSzd1gc4j/BjT2TXFNsJd2aL0G2ztttgQXs5Rh3p0txMemTEDx9XwO28kkw8goAjV7F+D04sCnhs6fV12POqdVhVPgGT1obFNE24ePingkuwWHWG9Uy+i7GPsGd5lz7E+lh73ZMvNvst3fppP9mSGTYwd7ig7RWCyovljFoVSYYi0h0lbJg3QU3+Nz+nMpFZ9fB1H34dFSkTXKpr00Ff1fsVgjnqwPBLlQutGzTWTGtrBdNPEToBNKceG3LFeR69nlbkIxBsxeLPb86GIJY48UeBGGoXH99WGqVs2F6hR66V9QjqyJNKyyZ78v+DtFKdiEa+ZTbLxo4egDyQ6jIvTsRBe81kunzGq8/AN8xv3NYp87JDk4gQ9uzpLEQ/ThselVPsh3g0hfRvkyEyZb3nedcIxkmOPLphhArHQT0P/DE+Tqs+2ufLk7gM+VbO3kbI80zbGMefGmTNW6cxK5l2+3zCHmfWdL+MFGKwLlqzSRpKFtA+axqNGXGXTOD9F0Ph5SHFv0x1W/5+PQ+qkQvYuAkaWMUvqmjqJJ4Kwx7JoRwSk1D0rSW1n028vE7240CRIAcKut8lifGvmy1EXsU3mFGS2v727yQibYc7fvlNgd39tbh7lTfMu4kratGm71J5PTa8SjuEmRvwuQs6b6qIa43WIPu3BYKFz0cGAVTYHk=
#   on:
#     tags: true